name: app_chan_doan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  cloud_firestore: ^5.4.2
  mqtt_client: ^10.3.0
  fl_chart: ^0.69.0
  rebi_vin_decoder: ^0.0.2
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/logoBK.png
  - assets/images/Actuators_Test.png
  - assets/images/Diagnostic.png
  - assets/images/GPS_Tracker.png
  - assets/images/Module_Information.png
  - assets/images/OBD_Test.png
  - assets/images/Read_Stream_Data.png
  - assets/images/On_Button.png
  - assets/images/Off_Button.png
  - assets/images/Search_DTC.png
  - assets/images/Stored_DTC.png
  - assets/images/Pending_DTC.png
  - assets/images/steering_wheel.png
  - assets/images/Radar_Chart.png
  - assets/images/login.jpg
  - assets/images/seri.jpg
  - assets/images/logout.png
  - assets/images/logoVNU.png
  - assets/images/logoGT.png
  - assets/images/logoFAST.png
  - assets/images/Xpander.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
