class mode_obj_info {
  late var value;

  late String name;

  late String unit;

  late String firebase_name;

  late int mode;

  late int pri_stat_1;
  late int pri_stat_2;

  bool status = false;

  mode_obj_info(
      {required this.name,
      required this.unit,
      required this.mode,
      required this.firebase_name,
      required this.pri_stat_1,
      required this.pri_stat_2});
}

List<mode_obj_info> listMode1info = [
  mode_obj_info(
    name: "Tải trọng của động cơ",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/CEL",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Nhiệt động nước làm mát",
    unit: "độ C",
    mode: 0x01,
    firebase_name: "/41/ET",
    pri_stat_1: 1,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Điều chỉnh nhiên liệu ngắn hạn - Dãy 1",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/STFT1",
    pri_stat_1: 2,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Điều chỉnh nhiên liệu dài hạn - Dãy 1",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/LTFT1",
    pri_stat_1: 3,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Áp suất tuyệt đối đường ống nạp",
    unit: "kPa",
    mode: 0x01,
    firebase_name: "/41/IMAP",
    pri_stat_1: 4,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Tốc độ động cơ",
    unit: "rpm",
    mode: 0x01,
    firebase_name: "/41/ES",
    pri_stat_1: 5,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Tốc độ của xe",
    unit: "km/h",
    mode: 0x01,
    firebase_name: "/41/VS",
    pri_stat_1: 6,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Góc đánh lửa sớm",
    unit: "độ trước TDC",
    mode: 0x01,
    firebase_name: "/41/TA",
    pri_stat_1: 7,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Nhiệt độ khí nạp",
    unit: "độ C",
    mode: 0x01,
    firebase_name: "/41/IAT",
    pri_stat_1: 8,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Vị trí bướm ga",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/TP",
    pri_stat_1: 9,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Cảm biến oxy đang hoạt động",
    unit: "",
    mode: 0x01,
    firebase_name: "/41/OSP",
    pri_stat_1: 10,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Điện áp cảm biến oxy 1",
    unit: "V",
    mode: 0x01,
    firebase_name: "/41/OSV1",
    pri_stat_1: 11,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Điều chỉnh nhiên liệu ngắn hạn cảm biến oxy 1",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/STFT1",
    pri_stat_1: 11,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Điện áp cảm biến oxy 2",
    unit: "V",
    mode: 0x01,
    firebase_name: "/41/OSV2",
    pri_stat_1: 12,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Điều chỉnh nhiên liệu ngắn hạn cảm biến oxy 2",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/STFT2",
    pri_stat_1: 12,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Tiêu chuẩn OBD",
    unit: "",
    mode: 0x01,
    firebase_name: "/41/OBDS",
    pri_stat_1: 13,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Thời gian kể từ khi khởi động động cơ",
    unit: "s",
    mode: 0x01,
    firebase_name: "/41/RTES",
    pri_stat_1: 14,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Quãng đường đã di chuyển",
    unit: "km",
    mode: 0x01,
    firebase_name: "/41/DT",
    pri_stat_1: 15,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Xả hơi nhiên liệu theo lệnh",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/CEP",
    pri_stat_1: 16,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Số lần đạt nhiệt độ làm việc sau khi xóa lỗi",
    unit: "",
    mode: 0x01,
    firebase_name: "/41/WSCC",
    pri_stat_1: 17,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Quãng đường đã đi từ khi các lỗi được xóa",
    unit: "km",
    mode: 0x01,
    firebase_name: "/41/DTCC",
    pri_stat_1: 18,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Áp suất khí quyển tuyệt đối",
    unit: "kPa",
    mode: 0x01,
    firebase_name: "/41/ABP",
    pri_stat_1: 19,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Điện áp mô đun điều khiển",
    unit: "V",
    mode: 0x01,
    firebase_name: "/41/CMV",
    pri_stat_1: 20,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Giá trị tải tuyệt đối",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/ALV",
    pri_stat_1: 21,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Tỷ lệ không khí-nhiên liệu điều khiển",
    unit: "ratio",
    mode: 0x01,
    firebase_name: "/41/CAFER",
    pri_stat_1: 22,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Vị trí tương đối của bướm ga",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/RTP",
    pri_stat_1: 23,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Nhiệt độ không khí xung quanh",
    unit: "độ C",
    mode: 0x01,
    firebase_name: "/41/AAT",
    pri_stat_1: 24,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Vị trí bướm ga tuyệt đối B",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/ATPB",
    pri_stat_1: 25,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Vị trí bàn đạp ga D",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/APPD",
    pri_stat_1: 26,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Vị trí bàn đạp ga E",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/APPE",
    pri_stat_1: 27,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Bộ chấp hành bướm ga điều khiển",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/CTA",
    pri_stat_1: 28,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Loại nhiên liệu",
    unit: "",
    mode: 0x01,
    firebase_name: "/41/FT",
    pri_stat_1: 29,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Vị trí tương đối của bàn đạp ga",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/RAPP",
    pri_stat_1: 30,
    pri_stat_2: 0,
  ),
];

List<mode_obj_info> listMode4info = [
  mode_obj_info(
    name: "Kim phun 1",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/IJ1",
    pri_stat_1: 0x10,
    pri_stat_2: 1,
  ),
  mode_obj_info(
    name: "Kim phun 2",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/IJ2",
    pri_stat_1: 0x10,
    pri_stat_2: 2,
  ),
  mode_obj_info(
    name: "Kim phun 3",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/IJ3",
    pri_stat_1: 0x10,
    pri_stat_2: 3,
  ),
  mode_obj_info(
    name: "Kim phun 4",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/IJ4",
    pri_stat_1: 0x10,
    pri_stat_2: 4,
  ),
  mode_obj_info(
    name: "Bơm nhiên liệu",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/ACT/11",
    pri_stat_1: 0x11,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Van kiểm soát xả hơi nhiên liệu",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/ACT/12",
    pri_stat_1: 0x12,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Góc đánh lửa 5 độ trước điểm chết trên",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/ACT/13",
    pri_stat_1: 0x13,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Van điện từ điều khiển thông gió",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/ACT/17",
    pri_stat_1: 0x17,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Rơ le máy nén điều hòa",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/ACT/18",
    pri_stat_1: 0x18,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Van điều khiển cấp dầu",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/ACT/19",
    pri_stat_1: 0x19,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Rơ le quạt làm mát (cao)",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/ACT/14",
    pri_stat_1: 0x14,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Rơ le quạt làm mát (thấp)",
    unit: "",
    mode: 0x30,
    firebase_name: "/70/ACT/15",
    pri_stat_1: 0x15,
    pri_stat_2: 0,
  ),
];

List<mode_obj_info> listMode6info = [
  mode_obj_info(
    name: "Dữ liệu đánh lửa sai xi lanh 1 (0B)",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/MCD1/0B",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Dữ liệu đánh lửa sai xi lanh 1 (0C)",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/MCD1/0C",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Dữ liệu đánh lửa sai xi lanh 2 (0B)",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/MCD2/0B",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Dữ liệu đánh lửa sai xi lanh 2 (0C)",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/MCD2/0C",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Dữ liệu đánh lửa sai xi lanh 3 (0B)",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/MCD3/0B",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Dữ liệu đánh lửa sai xi lanh 3 (0C)",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/MCD3/0C",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Dữ liệu đánh lửa sai xi lanh 4 (0B)",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/MCD4/0B",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Dữ liệu đánh lửa sai xi lanh 4 (0C)",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/MCD4/0C",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Cảm biến oxy Dãy 1 Cảm biến 1",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/OSBS",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Giám sát bộ chuyển hóa xúc tác",
    unit: "",
    mode: 0x06,
    firebase_name: "/46/CMB",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
];

List<mode_obj_info> listMode3info = [
  mode_obj_info(
    name: "DTC đã lưu trữ",
    unit: "",
    mode: 0x03,
    firebase_name: "/43/DTC",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
];

List<mode_obj_info> listMode7info = [
  mode_obj_info(
    name: "DTC đang xử lý",
    unit: "",
    mode: 0x07,
    firebase_name: "/47/DTC",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
];

List<mode_obj_info> listMode9info = [
  mode_obj_info(
    name: "Số VIN",
    unit: "",
    mode: 0x09,
    firebase_name: "/49/VIN",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
];

List<mode_obj_info> listRadarinfo = [
  mode_obj_info(
    name: "Tải trọng của động cơ",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/CEL",
    pri_stat_1: 0,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Nhiệt động nước làm mát",
    unit: "độ C",
    mode: 0x01,
    firebase_name: "/41/ET",
    pri_stat_1: 1,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Áp suất tuyệt đối đường ống nạp",
    unit: "kPa",
    mode: 0x01,
    firebase_name: "/41/IMAP",
    pri_stat_1: 4,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Tốc độ động cơ",
    unit: "rpm",
    mode: 0x01,
    firebase_name: "/41/ES",
    pri_stat_1: 5,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Tốc độ của xe",
    unit: "km/h",
    mode: 0x01,
    firebase_name: "/41/VS",
    pri_stat_1: 6,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Nhiệt độ khí nạp",
    unit: "độ C",
    mode: 0x01,
    firebase_name: "/41/IAT",
    pri_stat_1: 8,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Vị trí bướm ga",
    unit: "%",
    mode: 0x01,
    firebase_name: "/41/TP",
    pri_stat_1: 9,
    pri_stat_2: 0,
  ),
  mode_obj_info(
    name: "Điện áp mô đun điều khiển",
    unit: "V",
    mode: 0x01,
    firebase_name: "/41/CMV",
    pri_stat_1: 20,
    pri_stat_2: 0,
  ),
];